name: 'IntaPass Action'
description: 'AI code review solution that helps you write better software'
label: 'award'
color: 'black'
inputs:
  review_code:  # id of input
    description: 'Code Review'
    required: true
    default: 'Yes'
outputs:
  results: # id of output
    description: 'Here is the result of your output'
runs:
  using: 'node20'
  main: 'dist/index.js'
