on: [push]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: Review code and advise on best practices
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Get changed files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Code review
        id: review_code
        uses: intapass/intapass-action@0.0.3
        with:
          files: ${{ steps.files.outputs.all }}
      - name: Get the review results
        run: echo "Results ${{ steps.review_code.outputs.results }}"