on: [push]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: Review code and advise on best practices
    steps:
      - name: Code review
        id: review_code
        uses: intapass/intapass-action@alpha
        with:
          review_code: 'Yes'
      - name: Get the review results
        run: echo "The time was ${{ steps.code_review_job.outputs.results }}"